name: kubeportal-api-dev

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PUBLISH:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: registry.datexis.com/ksachs/kubeportal-api-dev:latest
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSPHRASE }}
          registry: registry.datexis.com
          snapshot: true
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Restart kubeportal-api-dev pod
        run: kubectl -n sachs delete pod -l app=kubeportal-api-dev
