kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: kubeportal-api-dev-ingress
  namespace: sachs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - kubeportal-dev.api.datexis.com
    secretName: kubeportal-api-dev-ingress-tls
  rules:
  - host: kubeportal-dev.api.datexis.com
    http:
      paths:
      - backend:
          serviceName: kubeportal-api-dev-service
          servicePort: 5000
